hey, a compressor! using default PCM ID. switchGears works too now
Team138Entropy/Entropy2020 pull request #51
Opened 2020-01-24 00:21 UTC by Team138Entropy

but it might be backwards. more testing required.

2020-01-24 01:52 UTC, maxh65000 requested changes
This should be its own subsystem. We don't want to be adding stuff that might not exist on a testbed to our code as it might prevent us from testing it on testbeds.

2020-01-28 00:34 UTC, maxh65000 approved these changes

2020-01-28 00:55 UTC, merged

2020-01-28 01:02 UTC, jhinspeter requested changes

2020-01-28 01:02 UTC, jhinspeter commented on src/main/java/frc/robot/Robot.java
>        boolean AutoDrive = false;
Local variables should use camelCase. Please convert all of these User Input variables

2020-01-28 01:02 UTC, jhinspeter commented on src/main/java/frc/robot/subsystems/Drive.java
> +  public synchronized void SwitchGears() {
What's the use case here? Are we truly just going to have one button that toggles between low and high gears? Are there situations where we will want to ensure we are in one or the other?

2020-01-28 01:22 UTC, Team138Entropy commented
Requested changes completed, see [#66](https://github.com/Team138Entropy/Entropy2020/pull/66)