Hardware integration
Team138Entropy/Entropy2020 pull request #85
Opened 2020-02-05 01:19 UTC by Team138Entropy

2020-02-05 01:50 UTC, maxh65000 approved these changes

2020-02-06 00:01 UTC, jhinspeter requested changes

2020-02-06 00:01 UTC, jhinspeter commented on src/main/java/frc/robot/Config.java
> +    //DRIVE__LEFT_FRONT_PORT()
Drive motors are using constants. Let's migrate them to config.

2020-02-06 00:01 UTC, jhinspeter commented on src/main/java/frc/robot/Robot.java
> +      mStorage.stopTop();
Let's change this over to `setTopOutput(0)`, and remove the `stopTop()` and `stopBottom()`

2020-02-06 00:01 UTC, jhinspeter commented on src/main/java/frc/robot/subsystems/Drive.java
> +  public void setOutputLeftBack (double output) {
Add function comments that clearly state these functions are for Test Mode only.

2020-02-06 00:01 UTC, jhinspeter commented on src/main/java/frc/robot/subsystems/Intake.java
> +  public void setOutput(double output) {
Add a function comment that states this function is for Test Mode only.

2020-02-06 00:01 UTC, jhinspeter commented on src/main/java/frc/robot/subsystems/Shooter.java
> +  public void setOutput(double output) {
Add a function comment that states the function is for Test Mode only.

2020-02-06 00:01 UTC, jhinspeter commented on src/main/java/frc/robot/subsystems/Storage.java
> +  // TODO: Need to implement top roller
No longer a TODO

2020-02-06 00:01 UTC, jhinspeter commented on src/main/java/frc/robot/subsystems/Storage.java
> +  public void stopBottom() {
Not needed. Use `setBottomOutput(0)` for test functionality instead.

2020-02-06 00:01 UTC, jhinspeter commented on src/main/java/frc/robot/subsystems/Storage.java
> +  public void stopTop() {
Not needed. Use `setTopOutput(0)` for test functionality instead.

2020-02-06 01:52 UTC, Team138Entropy commented on src/main/java/frc/robot/Robot.java
> +      mStorage.stopTop();
Done

2020-02-06 01:52 UTC, Team138Entropy commented on src/main/java/frc/robot/subsystems/Drive.java
> +  public void setOutputLeftBack (double output) {
All set

2020-02-06 01:52 UTC, Team138Entropy commented on src/main/java/frc/robot/subsystems/Intake.java
> +  public void setOutput(double output) {
Sure thing

2020-02-06 01:52 UTC, Team138Entropy commented on src/main/java/frc/robot/subsystems/Shooter.java
> +  public void setOutput(double output) {
Done deal

2020-02-06 01:52 UTC, Team138Entropy commented on src/main/java/frc/robot/subsystems/Storage.java
> +  // TODO: Need to implement top roller
TODO? More like GONE

2020-02-06 01:52 UTC, Team138Entropy commented on src/main/java/frc/robot/subsystems/Storage.java
> +  public void stopBottom() {
Yeeted

2020-02-06 01:52 UTC, Team138Entropy commented on src/main/java/frc/robot/subsystems/Storage.java
> +  public void stopTop() {
Excommunicated faster than Martin Luther

2020-02-06 01:52 UTC, Team138Entropy commented on src/main/java/frc/robot/Config.java
> +    //DRIVE__LEFT_FRONT_PORT()
Migrated like the Canadian Goose

2020-02-06 01:53 UTC, jhinspeter approved these changes

2020-02-06 01:55 UTC, merged